#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<center>"
echo "<h1>"
echo "Running application on Power on premises and x86 at AWS concurrently" 
echo "The PVCs for the application is on a single namespace replicated across multiple clouds"
echo "</h1>"
echo "<h1>"
echo "Today is $(date)"
echo "</h1>"
echo "<h1>"
echo "$(uname -a)"
echo "</h1>"
echo "<h1>"
echo SERVER_SOFTWARE = $SERVER_SOFTWARE
echo "</h1>"
echo "</center>"
